"""Email notification after each pipeline run.

Sends a summary email via Gmail SMTP (free, no third-party service needed).

Setup:
1. Go to https://myaccount.google.com/apppasswords
2. Create an App Password for "Mail" (requires 2FA enabled)
3. Set these secrets in GitHub Actions:
   - GMAIL_ADDRESS: your Gmail address
   - GMAIL_APP_PASSWORD: the 16-character app password
4. Or set them as environment variables for local runs
"""

from __future__ import annotations
import smtplib
import json
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import date
from pathlib import Path
from typing import List
from scrapers.base import Job


def send_summary_email(
    matched_jobs: List[Job],
    raw_count: int,
    unique_count: int,
    gmail_address: str,
    gmail_app_password: str,
    recipient: str = None,
) -> bool:
    """Send a daily summary email with matched jobs.

    Args:
        matched_jobs: List of matched Job objects
        raw_count: Total raw jobs scraped
        unique_count: Unique jobs after dedup
        gmail_address: Gmail address to send from
        gmail_app_password: Gmail App Password (not regular password)
        recipient: Email to send to (defaults to gmail_address)

    Returns:
        True if email sent successfully
    """
    recipient = recipient or gmail_address
    today = date.today().isoformat()

    all_85 = sum(
        1 for j in matched_jobs
        if j.ats_score >= 85 and j.hiring_manager_score >= 85 and j.tech_recruiter_score >= 85
    )

    # Build the email body
    subject = f"Job Hunt: {len(matched_jobs)} matches ({all_85} ready) — {today}"

    # HTML body for nice formatting
    html = f"""
    <html>
    <body style="font-family: -apple-system, Arial, sans-serif; max-width: 700px; margin: 0 auto;">
    <h2 style="color: #1F4E79;">Daily Job Hunt — {today}</h2>

    <table style="border-collapse: collapse; margin-bottom: 20px;">
        <tr><td style="padding: 4px 12px; color: #666;">Scraped:</td><td><strong>{raw_count}</strong></td></tr>
        <tr><td style="padding: 4px 12px; color: #666;">Unique:</td><td><strong>{unique_count}</strong></td></tr>
        <tr><td style="padding: 4px 12px; color: #666;">Matched:</td><td><strong>{len(matched_jobs)}</strong></td></tr>
        <tr><td style="padding: 4px 12px; color: #666;">All 3 scores 85+:</td><td><strong style="color: {'#2E7D32' if all_85 > 0 else '#C62828'};">{all_85}</strong></td></tr>
    </table>
    """

    if matched_jobs:
        html += """
        <h3 style="color: #1F4E79;">Top Matches</h3>
        <table style="border-collapse: collapse; width: 100%;">
        <tr style="background: #1F4E79; color: white;">
            <th style="padding: 8px; text-align: left;">Score</th>
            <th style="padding: 8px; text-align: left;">ATS/HM/TR</th>
            <th style="padding: 8px; text-align: left;">Title</th>
            <th style="padding: 8px; text-align: left;">Company</th>
            <th style="padding: 8px; text-align: left;">Apply</th>
        </tr>
        """

        for i, job in enumerate(matched_jobs[:15]):
            bg = "#f2f2f2" if i % 2 == 0 else "#ffffff"
            score_color = "#2E7D32" if job.match_score >= 85 else "#F57F17" if job.match_score >= 70 else "#C62828"
            apply_link = f'<a href="{job.apply_url}" style="color: #0563C1;">Apply</a>' if job.apply_url else "—"

            # LinkedIn contacts
            contact_links = ""
            if job.linkedin_contacts:
                try:
                    contacts = json.loads(job.linkedin_contacts)
                    for c in contacts[:2]:
                        url = c.get("search_url", "")
                        role = c.get("role", "")
                        if url:
                            contact_links += f' | <a href="{url}" style="color: #0563C1; font-size: 11px;">{role}</a>'
                except json.JSONDecodeError:
                    pass

            html += f"""
            <tr style="background: {bg};">
                <td style="padding: 8px; color: {score_color}; font-weight: bold;">{job.match_score}</td>
                <td style="padding: 8px; font-size: 11px;">{job.ats_score}/{job.hiring_manager_score}/{job.tech_recruiter_score}</td>
                <td style="padding: 8px;">{job.title}</td>
                <td style="padding: 8px;">{job.company}</td>
                <td style="padding: 8px;">{apply_link}{contact_links}</td>
            </tr>
            """

        html += "</table>"

    html += """
    <p style="margin-top: 20px; color: #999; font-size: 12px;">
        Generated by your Job Automation Pipeline. Check the master tracker for full details.
    </p>
    </body>
    </html>
    """

    # Plain text fallback
    plain = f"Daily Job Hunt — {today}\n\n"
    plain += f"Scraped: {raw_count} | Unique: {unique_count} | Matched: {len(matched_jobs)} | All 85+: {all_85}\n\n"
    for job in matched_jobs[:10]:
        plain += f"[{job.match_score}] {job.title} @ {job.company} — {job.apply_url}\n"

    # Build email
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = gmail_address
    msg["To"] = recipient
    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(gmail_address, gmail_app_password)
            server.send_message(msg)
        print(f"  [EMAIL] Summary sent to {recipient}")
        return True
    except Exception as e:
        print(f"  [EMAIL] Failed to send: {e}")
        return False
