"""UserProfile dataclass — central user abstraction for the job automation pipeline.

Replaces hardcoded user data scattered across matcher.py, tailorer.py,
cover_letter.py, and other modules. Supports two construction paths:

  * from_db_row()  — for multi-tenant SaaS (loaded from Supabase users table)
  * from_config()  — for single-user mode (loaded from config.yaml profile section)
                     preserves backward compatibility during the transition

The pipeline should pass a UserProfile instance around rather than reaching
into config dicts or hardcoding strings like "Utkarsh_Singh".
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass, field
from typing import Dict


@dataclass
class UserProfile:
    """All user-specific data required by the job automation pipeline.

    Parameters
    ----------
    id:
        UUID from Supabase auth (or a deterministic UUID derived from email
        when running in single-user / config-only mode).
    email:
        Primary contact email (used in cover letter headers and email notifications).
    name:
        Full name as it should appear on resumes and cover letters.
    phone:
        Phone number string, e.g. "+353 892515620".
    location:
        City/country string, e.g. "Dublin, Ireland".
    visa_status:
        Free-text visa description, e.g. "Stamp 1G - eligible for full-time employment".
    github:
        Full GitHub profile URL.
    linkedin:
        Full LinkedIn profile URL.
    website:
        Personal website / portfolio URL.
    work_authorizations:
        Mapping of country/region keys to authorization description strings,
        e.g. {"ireland": "Stamp 1G - full-time eligible", "us": "Requires sponsorship"}.
    candidate_context:
        Free-text blob used to inject candidate info into AI prompts. When
        empty, auto-generated by to_candidate_context().
    """

    id: str
    email: str
    name: str
    phone: str = ""
    location: str = ""
    visa_status: str = ""
    github: str = ""
    linkedin: str = ""
    website: str = ""
    work_authorizations: Dict[str, str] = field(default_factory=dict)
    candidate_context: str = ""

    # ── Construction helpers ──────────────────────────────────────────────

    @classmethod
    def from_db_row(cls, row: dict) -> "UserProfile":
        """Create a UserProfile from a Supabase ``users`` table row.

        All columns in the row map directly to dataclass fields. Extra columns
        (e.g. created_at, gdpr_consent_at) are silently ignored so this stays
        forward-compatible with schema changes.

        Parameters
        ----------
        row:
            Dict returned by SupabaseClient.get_user() or equivalent query.
        """
        known_fields = {
            "id", "email", "name", "phone", "location", "visa_status",
            "github", "linkedin", "website", "work_authorizations",
            "candidate_context",
        }
        filtered = {k: v for k, v in row.items() if k in known_fields and v is not None}
        return cls(**filtered)

    @classmethod
    def from_config(cls, config: dict) -> "UserProfile":
        """Create a UserProfile from the ``profile`` section of config.yaml.

        Provides backward compatibility for the single-user pipeline so it can
        keep running without Supabase during the multi-tenant transition. The
        ``id`` field is set to a deterministic UUID-format string derived from
        the email address so downstream code that needs a user ID still works.

        Parameters
        ----------
        config:
            The full config dict (as loaded by ``yaml.safe_load``).  Reads the
            ``config["profile"]`` sub-dict.
        """
        profile = config.get("profile", {})
        email = profile.get("email", "")

        # Deterministic UUID-like ID from email so single-user runs have a
        # stable ID without requiring Supabase.
        id_ = _deterministic_uuid(email)

        return cls(
            id=id_,
            email=email,
            name=profile.get("name", ""),
            phone=profile.get("phone", ""),
            location=profile.get("location", ""),
            visa_status=profile.get("visa_status", ""),
            github=profile.get("github", ""),
            linkedin=profile.get("linkedin", ""),
            website=profile.get("website", ""),
            work_authorizations=dict(profile.get("work_authorization", {})),
            # candidate_context is not stored in config.yaml; auto-generated on demand.
            candidate_context="",
        )

    # ── Derived properties ────────────────────────────────────────────────

    def to_candidate_context(self) -> str:
        """Return the candidate context string injected into AI prompts.

        If ``self.candidate_context`` is non-empty (e.g. set by the user via
        the onboarding form or loaded from the DB), it is returned as-is.

        Otherwise a context block is auto-generated from the profile fields:

        Example output::

            Based in Dublin, Ireland. Stamp 1G visa.
            Work authorizations:
              * Ireland: Stamp 1G - full-time eligible
              * India: Indian citizen - full-time eligible
              * US: Requires sponsorship (H-1B/L-1)
        """
        if self.candidate_context:
            return self.candidate_context

        lines: list[str] = []

        if self.location:
            line = f"Based in {self.location}."
            if self.visa_status:
                line += f" {self.visa_status}."
            lines.append(line)

        if self.work_authorizations:
            lines.append("Work authorizations:")
            for region, description in self.work_authorizations.items():
                lines.append(f"  * {region.capitalize()}: {description}")

        return "\n".join(lines)

    def safe_filename_prefix(self) -> str:
        """Return a filename-safe version of the user's full name.

        Replaces spaces with underscores and strips any character that is not
        alphanumeric or an underscore.  Used as the prefix for generated
        resume and cover letter filenames, e.g. "Utkarsh_Singh".

        Falls back to the email prefix (before @) if name is empty.
        """
        if self.name:
            slug = self.name.replace(" ", "_")
            slug = re.sub(r"[^\w]", "", slug)
            if slug:
                return slug
        # Fallback: derive from email prefix
        if self.email:
            return self.email.split("@")[0].replace(".", "_")
        return "User"

    def to_dict(self) -> dict:
        """Serialize to a plain dict suitable for DB storage or JSON responses."""
        return {
            "id": self.id,
            "email": self.email,
            "name": self.name,
            "phone": self.phone,
            "location": self.location,
            "visa_status": self.visa_status,
            "github": self.github,
            "linkedin": self.linkedin,
            "website": self.website,
            "work_authorizations": self.work_authorizations,
            "candidate_context": self.candidate_context,
        }


# ── Module-private helpers ────────────────────────────────────────────────────

def _deterministic_uuid(seed: str) -> str:
    """Return a deterministic UUID v4-format string derived from *seed*.

    Uses the MD5 hash of the seed bytes, then tweaks nibbles 13 and 17 to
    conform to the UUID v4 / variant-1 format (``xxxxxxxx-xxxx-4xxx-yxxx-…``).
    This is not cryptographically random — it is only used to give single-user
    pipeline runs a stable, consistent user ID.
    """
    digest = hashlib.md5(seed.encode("utf-8")).hexdigest()
    # Insert hyphens: 8-4-4-4-12
    parts = [digest[:8], digest[8:12], digest[12:16], digest[16:20], digest[20:32]]
    uuid_str = "-".join(parts)

    # Force version nibble to '4' (position 14 in the canonical string, index 2 in parts[2])
    p2 = list(parts[2])
    p2[0] = "4"
    # Force variant nibble to '8'-'b' range (position 19, index 0 in parts[3])
    variant_hex = format((int(parts[3][0], 16) & 0x3) | 0x8, "x")
    p3 = list(parts[3])
    p3[0] = variant_hex

    return f"{parts[0]}-{parts[1]}-{''.join(p2)}-{''.join(p3)}-{parts[4]}"
